# Automatic releases: http://docs.travis-ci.com/user/deployment/releases/

language: cpp

compiler:
    - g++
    - clang++

script: make build-run

notifications:
  email:
    on_success: change # always, never, change
    on_failure: change # always, never, change
