# Automatic releases: http://docs.travis-ci.com/user/deployment/releases/

language: cpp

# Source for installation stages: http://gearchicken.com/wordpress/?p=105
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
# We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 9

script: make build-run

notifications:
  email:
    on_success: change # always, never, change
    on_failure: change # always, never, change
